
services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx
    depends_on:
      - gateway

  gateway:
    container_name: gateway
    build:
      ./
    command: uvicorn main:gateway --host 0.0.0.0 --port 7300
    ports:
      - "7300:7300"
    command: uvicorn main:app --host 0.0.0.0 --port $PORT
    networks:
      - sql
      - nginx

networks:
  sql:
    external: true
  nginx:
    external: true
