version: "3.8"

services:

  gateway:
    container_name: gateway
    build:
      ./
    command: uvicorn main:app --host 0.0.0.0 --port $PORT
    networks:
      - sql

networks:
  sql:
    external: true
